### ISSUE TITLE
Tiles does not merge correctly

### ISSUE THREAD

**Issue by stepankuzmin** [mojodna/tilelive-merge#2]
Hi! I've tried this package and have a strange issue. It does not appear constantly, but it appears very often.

I've got two sets of tiles (`a.mbtiles` and `b.mbtiles`).
I've setup project using tilelive-merge and mapbox-gl-js.

On the first tile, my sources merges correctly (`a.mbtiles` is red and `b.mbtiles` is blue)
![screen shot 2015-06-05 at 16 05 04](https://cloud.githubusercontent.com/assets/533564/8004891/49eba40a-0b9d-11e5-8fac-992ecb44b8da.png)

After I zoom in a bit (server does not get request for another tile), `b.mbtiles` dissappears completely
![screen shot 2015-06-05 at 16 05 21](https://cloud.githubusercontent.com/assets/533564/8004905/7d2ed09e-0b9d-11e5-8dbc-ae6078883b19.png)

After I zoom in a bit more,  `b.mbtiles` appears, but partially (a and b must intersects)
![screen shot 2015-06-05 at 16 06 01](https://cloud.githubusercontent.com/assets/533564/8004921/aae885d4-0b9d-11e5-8b9f-71adffefe7c5.png)

So where is problem can be? Is it mapbox-gl-js or tilelive-merge package?

**Comment by sethfitz** [comment]
I suspect tilelive-merge, probably something related to the TileJSON associated with each MBTiles, as that informs whether it attempts to overzoom or not.  Mind posting that?

(Using [tessera](https://github.com/mojodna/tessera), you can go to `/index.json` to pull it.)

**Comment by stepankuzmin** [comment]
Thanks for reply, @mojodna. TileJSON for `a.mbtiles`

``` json
{
  "scheme": "tms",
  "basename": "a.mbtiles",
  "id": "a",
  "filesize": 177152,
  "center": [-55.8984, 26.4312, 0],
  "format": "pbf",
  "maxzoom": 6,
  "minzoom": 0,
  "vector_layers": [{
    "id": "a",
    "description": "",
    "fields": {
      "id": "Number"
    }
  }],
  "bounds": [-180, -85.05112877980659, 180, 85.0511287798066],
  "name": "Untitled",
  "tiles": ["http://localhost:8080/{z}/{x}/{y}.pbf"],
  "tilejson": "2.0.0"
}
```

TileJSON for `b.mbtiles`

``` json
{
  "scheme": "tms",
  "basename": "b.mbtiles",
  "id": "b",
  "filesize": 155648,
  "center": [-53.4375, 86.3576, 0],
  "format": "pbf",
  "maxzoom": 6,
  "minzoom": 0,
  "vector_layers": [{
    "id": "b",
    "description": "",
    "fields": {
      "id": "Number"
    }
  }],
  "bounds": [-180, -85.05112877980659, 180, 85.0511287798066],
  "name": "Untitled",
  "tiles": ["http://localhost:8080/{z}/{x}/{y}.pbf"],
  "tilejson": "2.0.0"
}
```

Resulting TileJSON for `a.mbtiles` and `b.mbtiles` using `tilelive.info`

``` json
{
  "description": "",
  "bounds": [-180, -85.05112877980659, 180, 85.0511287798066],
  "center": [-55.8984, 26.4312, 0],
  "format": "pbf",
  "maxzoom": 6,
  "minzoom": 0,
  "name": " + ",
  "scheme": "tms",
  "vector_layers": [{
    "id": "a",
    "description": "",
    "fields": {
      "id": "Number"
    }
  }, {
    "id": "b",
    "description": "",
    "fields": {
      "id": "Number"
    }
  }],
  "id": "a,b",
  "version": "1.0.0",
  "legend": null,
  "tiles": ["http://localhost:8888/{z}/{x}/{y}.pbf"]
}
```

**Comment by sethfitz** [comment]
Hmm.  Nothing obvious there.  Are you able to share the MBTiles archives and point me at either the tile or geographic coordinates that aren't compositing correctly?

When requesting the area of interest, do you see if making requests to both of the MBTiles sources?

**Comment by stepankuzmin** [comment]
Thanks for reply, @mojodna! Something strange happened, I can not reproduce this bug again. I didn't change any code, but now it works as expected. So thanks again, closing issue.

**Comment by sethfitz** [comment]
Weird!  Glad to hear it.  If it crops up again, feel free to reopen.
