### ISSUE TITLE
overzooming issue

### ISSUE THREAD

**Issue by flemmens** [mojodna/tilelive-merge#3]
It seems there is an issue with overzooming when combining multiple sources with different zoom limits.

I use a mapbox source and a local source of vector tiles which contains zooms 1 to 9.
merge:?source=mapbox:///mapbox.mapbox-streets-v5&source=mbtiles:/home/data/mytiles.mbtiles

Up to zoom 9 everything is working fine, but when I zoom over level 9, the mapbox source is correctly rendered but my local source is not overzoomed and the tiles seems to be displayed randomly on the map.

If I use my local source only (mbtiles:/home/data/mytiles.mbtiles) the overzooming works well.

**Comment by sethfitz** [comment]
Good find.  Are you able to reproduce this using the xray view (i.e. when `tessera` serves up the merged source vs. applying a style to it)?

Can you share the MBTiles archive (privately or otherwise) with me so I can reproduce and figure out how to fix it?  (It'll save me creating my own.)

**Comment by flemmens** [comment]
The file I used was to big to be sent but I made a new test from scratch and I got exactly the same issue. Here are my process:
- I use a geojson file with locality boundaries in the Netherlands
- I create the pbf mbtiles using tippecanoe, from zoom 0 to 8
- I render the tiles with a mapbox style and tessera
- The source in the project.yml is:
  source: "merge:?source=mapbox:///mapbox.mapbox-streets-v6&source=mbtiles:/home/tiles/basic.tm2/nl.mbtiles"

Up to zoom 8 (the maximum in my nl.mbtiles file), everything is working, at upper levels you can check the result by yourself with these screenshots. I tried with several mbtiles containing different zoom levels, the issue always begin once overzooming is needed.

Zoom 8: OK
![zoom8](https://cloud.githubusercontent.com/assets/1489018/9959929/ba285660-5e17-11e5-96de-752c8db1e472.png)

Zoom 9:
![zoom9](https://cloud.githubusercontent.com/assets/1489018/9959928/ba27c074-5e17-11e5-96eb-0bb94af8c309.png)

Zoom 11:
![zoom11](https://cloud.githubusercontent.com/assets/1489018/9959930/ba296816-5e17-11e5-8c31-eb2ead57e495.png)

**Comment by flemmens** [comment]
Any news on this ?

**Comment by sethfitz** [comment]
Alas, no.  Honestly, needing to create a test file is my biggest mental block (aside from my lack of time this week), so if there's any way you could write out instructions to create it, I would really appreciate it.

**Comment by flemmens** [comment]
No problem, I can create some test files ready to use for you. I will send you that tomorrow as it is too late for me now. Is there any way to attach the file within this discussion ? If not how can I send them to you ?

**Comment by sethfitz** [comment]
Dropbox, S3, some sort of publicly-accessible location.  Mapbox even, as I can download the MBTiles archive directly.  (GitHub only does images.)

Tomorrow is great, thanks a ton!!

**Comment by flemmens** [comment]
Hi,
Here is a download link with a full sample:
https://www.dropbox.com/s/entm5b9ct9zrg0c/tlmerge.zip?dl=0

You will find 2 mbtiles files with the same source data:
- export1.mbtiles contains a layer called "reg10" with vector tiles from zoom 0 to 10
- export2.mbtiles contains a layer called "reg14" with vector tiles from zoom 0 to 14

Then I made 3 mapbox stylesheets:
- test10.tm2, which use export1, overzooming works perfectly:
  
  > tessera tmstyle://./test10.tm2
- test14.tm2, which use export2, overzooming works also perfectly
  
  > tessera tmstyle://./test14.tm2
- testmerge.tm2, which use both mbtiles, works fine up to zoom 10, from 11 we have the issue.
  
  > tessera tmstyle://./testmerge.tm2

(nb: you probably will have to change the mbtiles directory in project.yml)

Hope it will help !

**Comment by sethfitz** [comment]
Awesome, thank you!!!

**Comment by sethfitz** [comment]
Before:

![image](https://cloud.githubusercontent.com/assets/45/10120757/50eed5a0-6481-11e5-8b45-39e93efc2b41.png)

After:

![image](https://cloud.githubusercontent.com/assets/45/10120753/2df101c2-6481-11e5-8c07-9282d65be4e6.png)

(I switched up the colors and used `comp-op: plus;` to make the changes a little more obvious.)

There are still a few artifacts, but they're more likely to be geometry / clipping-related (and thus in Mapnik) than overzoom-related:

![image](https://cloud.githubusercontent.com/assets/45/10120761/91c79148-6481-11e5-8df1-ddf1db64cce9.png)

From http://localhost:8080/#11/52.3527/5.4757

This has been published to npm as v1.0.1.

Thanks a ton for your help reproducing this!!

**Comment by flemmens** [comment]
Thanks for the quick fix Seth ! I'm gonna try this right away.
